version: "3"

services:
  api:
    build: .
    command: sh -c "npm run typeorm migration:run && npm run dev"
    container_name: elearning_api
    hostname: elearning_api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    environment:
      - .env
  postgres:
    restart: on-failure
    image: postgres:latest
    container_name: elearning_postgres
    hostname: elearning_postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: elearning
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  # mongodb:
  #   restart: on-failure
  #   image: mongo:latest
  #   container_name: mongodb
  #   hostname: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data/mongo:/data/db
  # redis:
  #   restart: on-failure
  #   image: redis:alpine
  #   container_name: redis
  #   hostname: redis
  #   ports:
  #     - "6379:6379"
